# Generated by Django 5.0 on 2025-12-15 08:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee", "0004_alter_employee_create_by_alter_employee_id_and_more"),
        (
            "organization",
            "0002_alter_organization_create_by_alter_organization_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceCycle",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID，采用UUID生成",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="逻辑删除标识（禁止物理删除）",
                        verbose_name="逻辑删除标识",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="创建时间（禁止手动修改）",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "create_by",
                    models.CharField(
                        help_text="创建人（关联用户表 ID）",
                        max_length=64,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="更新时间（触发器自动更新）",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "update_by",
                    models.CharField(
                        help_text="更新人（关联用户表 ID）",
                        max_length=64,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "cycle_name",
                    models.CharField(max_length=100, verbose_name="周期名称"),
                ),
                (
                    "cycle_type",
                    models.CharField(
                        choices=[
                            ("monthly", "月度"),
                            ("quarterly", "季度"),
                            ("semiannual", "半年度"),
                            ("annual", "年度"),
                        ],
                        max_length=20,
                        verbose_name="周期类型",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "未开始"),
                            ("in_progress", "进行中"),
                            ("ended", "已结束"),
                            ("archived", "已归档"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        help_text="空表示全公司",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.organization",
                        verbose_name="适用组织",
                    ),
                ),
            ],
            options={
                "verbose_name": "绩效周期",
                "verbose_name_plural": "绩效周期",
                "db_table": "performance_cycle",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceIndicatorSet",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID，采用UUID生成",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="逻辑删除标识（禁止物理删除）",
                        verbose_name="逻辑删除标识",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="创建时间（禁止手动修改）",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "create_by",
                    models.CharField(
                        help_text="创建人（关联用户表 ID）",
                        max_length=64,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="更新时间（触发器自动更新）",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "update_by",
                    models.CharField(
                        help_text="更新人（关联用户表 ID）",
                        max_length=64,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "set_name",
                    models.CharField(max_length=100, verbose_name="指标集名称"),
                ),
                (
                    "total_weight",
                    models.PositiveSmallIntegerField(
                        default=100, help_text="固定100", verbose_name="总权重"
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicator_sets",
                        to="performance.performancecycle",
                        verbose_name="关联周期",
                    ),
                ),
            ],
            options={
                "verbose_name": "绩效指标集",
                "verbose_name_plural": "绩效指标集",
                "db_table": "performance_indicator_set",
            },
        ),
        migrations.CreateModel(
            name="PerformanceEvaluation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID，采用UUID生成",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="逻辑删除标识（禁止物理删除）",
                        verbose_name="逻辑删除标识",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="创建时间（禁止手动修改）",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "create_by",
                    models.CharField(
                        help_text="创建人（关联用户表 ID）",
                        max_length=64,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="更新时间（触发器自动更新）",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "update_by",
                    models.CharField(
                        help_text="更新人（关联用户表 ID）",
                        max_length=64,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "self_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="自评总分",
                    ),
                ),
                (
                    "manager_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="上级评估总分",
                    ),
                ),
                (
                    "final_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="最终总分",
                    ),
                ),
                (
                    "final_remark",
                    models.TextField(blank=True, null=True, verbose_name="最终评价"),
                ),
                (
                    "evaluation_status",
                    models.CharField(
                        choices=[
                            ("not_started", "未开始"),
                            ("self_eval", "自评中"),
                            ("manager_eval", "上级评估中"),
                            ("hr_audit", "HR审核中"),
                            ("completed", "已完成"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="评估状态",
                    ),
                ),
                (
                    "appeal_status",
                    models.CharField(
                        choices=[
                            ("none", "无申诉"),
                            ("pending", "申诉中"),
                            ("approved", "申诉通过"),
                            ("rejected", "申诉拒绝"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="申诉状态",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="performance.performancecycle",
                        verbose_name="绩效周期",
                    ),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                        verbose_name="被评估人",
                    ),
                ),
                (
                    "indicator_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="performance.performanceindicatorset",
                        verbose_name="指标集",
                    ),
                ),
            ],
            options={
                "verbose_name": "绩效评估",
                "verbose_name_plural": "绩效评估",
                "db_table": "performance_evaluation",
            },
        ),
    ]
