# Generated by Django 5.0 on 2025-12-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0002_cycle_rules_and_auto_metrics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="performanceevaluation",
            name="indicator_set",
        ),
        migrations.RemoveField(
            model_name="performanceevaluation",
            name="manager_score",
        ),
        migrations.RemoveField(
            model_name="performanceevaluation",
            name="self_score",
        ),
        migrations.AlterField(
            model_name="performanceevaluation",
            name="evaluation_status",
            field=models.CharField(
                choices=[
                    ("not_started", "未开始"),
                    ("self_eval", "自评中"),
                    ("manager_eval", "上级评估中"),
                    ("hr_audit", "绩效部门审核中"),
                    ("completed", "已完成"),
                ],
                default="not_started",
                max_length=20,
                verbose_name="评估状态",
            ),
        ),
        migrations.DeleteModel(
            name="PerformanceIndicatorSet",
        ),
    ]
