# Generated by Django 5.0 on 2025-12-15 08:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leavetimesegment_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapply',
            name='create_by',
            field=models.CharField(help_text='创建人（关联用户表 ID）', max_length=64, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='leaveapply',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID，采用UUID生成', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leaveapply',
            name='update_by',
            field=models.CharField(help_text='更新人（关联用户表 ID）', max_length=64, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='leavetimesegment',
            name='create_by',
            field=models.CharField(help_text='创建人（关联用户表 ID）', max_length=64, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='leavetimesegment',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID，采用UUID生成', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leavetimesegment',
            name='update_by',
            field=models.CharField(help_text='更新人（关联用户表 ID）', max_length=64, verbose_name='更新人'),
        ),
    ]
