# Generated by Django 5.0 on 2025-12-15 07:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID，采用UUID生成', max_length=32, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, help_text='逻辑删除标识（禁止物理删除）', verbose_name='逻辑删除标识')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间（禁止手动修改）', verbose_name='创建时间')),
                ('create_by', models.CharField(help_text='创建人（关联用户表 ID）', max_length=32, verbose_name='创建人')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间（触发器自动更新）', verbose_name='更新时间')),
                ('update_by', models.CharField(help_text='更新人（关联用户表 ID）', max_length=32, verbose_name='更新人')),
                ('org_code', models.CharField(help_text='组织编码，全局唯一', max_length=50, unique=True, verbose_name='组织编码')),
                ('org_name', models.CharField(max_length=100, verbose_name='组织名称')),
                ('org_type', models.CharField(choices=[('company', '公司'), ('department', '部门'), ('team', '团队'), ('project_group', '项目组')], max_length=20, verbose_name='组织类型')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '禁用')], default='enabled', max_length=20, verbose_name='状态')),
                ('effective_time', models.DateTimeField(verbose_name='生效时间')),
                ('expire_time', models.DateTimeField(blank=True, help_text='失效时间（永久有效为空）', null=True, verbose_name='失效时间')),
                ('manager_emp', models.ForeignKey(blank=True, help_text='负责人工号（关联员工表）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orgs', to='employee.employee', verbose_name='负责人')),
                ('parent_org', models.ForeignKey(blank=True, help_text='上级组织ID（顶级节点为空）', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='organization.organization', verbose_name='上级组织')),
            ],
            options={
                'verbose_name': '组织结构',
                'verbose_name_plural': '组织结构',
                'db_table': 'organization',
                'ordering': ['org_code'],
            },
        ),
    ]
