# Generated by Django 5.0 on 2025-12-15 07:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID，采用UUID生成', max_length=32, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, help_text='逻辑删除标识（禁止物理删除）', verbose_name='逻辑删除标识')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间（禁止手动修改）', verbose_name='创建时间')),
                ('create_by', models.CharField(help_text='创建人（关联用户表 ID）', max_length=32, verbose_name='创建人')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间（触发器自动更新）', verbose_name='更新时间')),
                ('update_by', models.CharField(help_text='更新人（关联用户表 ID）', max_length=32, verbose_name='更新人')),
                ('field_name', models.CharField(max_length=50, verbose_name='变更字段')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='旧值')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='新值')),
                ('change_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='变更原因')),
            ],
            options={
                'verbose_name': '员工变更历史',
                'verbose_name_plural': '员工变更历史',
                'db_table': 'employee_history',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID，采用UUID生成', max_length=32, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, help_text='逻辑删除标识（禁止物理删除）', verbose_name='逻辑删除标识')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间（禁止手动修改）', verbose_name='创建时间')),
                ('create_by', models.CharField(help_text='创建人（关联用户表 ID）', max_length=32, verbose_name='创建人')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间（触发器自动更新）', verbose_name='更新时间')),
                ('update_by', models.CharField(help_text='更新人（关联用户表 ID）', max_length=32, verbose_name='更新人')),
                ('emp_id', models.CharField(help_text='员工工号（业务唯一标识，区别于系统ID）', max_length=32, unique=True, verbose_name='工号')),
                ('id_card', models.CharField(help_text='身份证号（加密存储，脱敏显示）', max_length=18, unique=True, verbose_name='身份证号')),
                ('emp_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10, verbose_name='性别')),
                ('birth_date', models.DateField(verbose_name='出生日期')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='邮箱')),
                ('hire_date', models.DateField(verbose_name='入职日期')),
                ('position', models.CharField(max_length=50, verbose_name='岗位名称')),
                ('employment_type', models.CharField(choices=[('full_time', '正式'), ('intern', '实习'), ('contract', '劳务派遣')], max_length=20, verbose_name='雇佣类型')),
                ('emp_status', models.CharField(choices=[('probation', '试用期'), ('active', '在职'), ('resigning', '待离职'), ('resigned', '离职'), ('suspended', '停薪留职')], max_length=20, verbose_name='员工状态')),
                ('manager_emp', models.ForeignKey(blank=True, help_text='直接上级工号', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employee.employee', verbose_name='直接上级')),
            ],
            options={
                'verbose_name': '员工档案',
                'verbose_name_plural': '员工档案',
                'db_table': 'employee',
                'ordering': ['emp_id'],
            },
        ),
    ]
