# Generated by Django 5.0 on 2025-12-16 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_record_id'),
        ('audit', '0002_alter_record_id'),
    ]

    operations = [
    ]
